### ISSUE TITLE
Propose renaming the repo

### ISSUE THREAD

**Issue by matthewberryman** [DarrinTisdale/zsh-aliases-exa#4]
While #3 addresses the rename more fully in the docs, oh-my-zsh gets confused (breaks the plugin) if the directory name doesn't match the name of the plugin file. E.g.
```shell
cd ~/.oh-my-zsh/custom/plugins
git clone https://github.com/DarrinTisdale/zsh-aliases-exa.git
```

with `plugins=(zsh-aliases-eza ...` or the older `plugins=(zsh-aliases-exa...`, whereas:
```shell
cd ~/.oh-my-zsh/custom/plugins
git clone https://github.com/DarrinTisdale/zsh-aliases-exa.git zsh-aliases-eza
```
works with `plugins=(zsh-aliases-eza ...` as now documented in #3 

I propose renaming the repo to `zsh-aliases-eza` (github will setup an automatic redirect from the old name), which fixes the issue.

**Comment by p1r473** [comment]
As well, the readme needs updating

**Comment by matthewberryman** [comment]
@p1r473 there's a [PR for updating the README](https://github.com/DarrinTisdale/zsh-aliases-exa/pull/3) that I opened a while ago, however this repo seems superfluous now there's an official plugin for eza https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/eza
